### ISSUE TITLE
Session save path is not a valid directory

### ISSUE THREAD

**Issue by supergithubo** [kartik-v/yii2-app-practical#17]
I'm having an error when accessing http://domain/app/ (fresh install).

```
Invalid Parameter – yii\base\InvalidParamException

Session save path is not a valid directory: 
..\frontend\config/../runtime/sessions
```

Also happens in ... http://domain/app/backend/web/

```
Invalid Parameter – yii\base\InvalidParamException

Session save path is not a valid directory: 
..\backend\config/../runtime/sessions
```

I have to manually add sessions folder to get rid of the error or did I just miss some configuration?

**Comment by kartik-v** [comment]
Actually this is an enhancement added recenty. Will push a fix... in the interim you can create a sessions folder on your runtime directory for this.
